server:
  port: 8080
  context-path: /

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000

    auth:
      path: /uaa/**
      url: http://localhost:9999/uaa


security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize

      client-id: acme
      client-secret: acmesecret
    resource:
      user-info-uri: http://localhost:9999/uaa/user

spring:
  devtools:
    livereload:
      enabled: true


