server:
  port: 8080
  context-path: /

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9999/uaa/user
  user:
    password: none


spring:
  devtools:
    livereload:
      enabled: true


